### ISSUE TITLE
RFE: Factory object to create a Session/wrapper based on a koji profile name

### ISSUE THREAD

**Issue by yazug** [release-depot/koji_wrapper#37]
Similar to how the koji --profile cli works to search your configs for a profile by that name.  It might be nice to have a "Factory" object or something else you can ask for a session/wrapper pointing at a defined koji profile, instead of having to specify url/params explicitly.

**Comment by jguiditta** [comment]
My thought coming into this was that we would eventually support a config file being passed in, which any client projects can use to store the urls they need to use.  It would looks something like:
```
repos:
  - name: mykoji
    url: http://something
    topurl: http://hub
  - name: mybrew
    url: http://something-else
    topurl: http://hub-bub
```
Then a client could pass in the config file, and if there is more than one koji instance specified in it, they could use the name (or something else, open to ideas) to tell us which one they want to use with THIS instance of koji_wrapper objects
